-- liquibase formatted sql
-- changeset EgorBystrov:1
-- comment: Create tables for Task1

create TABLE Method
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    method_name varchar(100)
);

create TABLE TrackTime
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    method_id int REFERENCES Method(id) ON DELETE SET NULL,
    execution_time BIGINT
);